version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker-compose
          command:  |
              curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose &&
              chmod +x /usr/local/bin/docker-compose
      - run:
          name: Checking installed versions
          command: docker --version && docker-compose --version
      - run:
          name: Build images
          command: docker-compose build
      - run:
          name: Check images list
          command: docker images