version: 2
jobs:
  build:
    working_directory: /repo
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command:  |
               apk add --no-cache \
                 py-pip=9.0.1-r1
               pip install \
                 docker-compose==1.19.0 \
      - run:
          name: Build application Docker image
          command: docker-compose build
      - run:
          name: List images
          command: docker images