#!/bin/sh
set -e

#
# Add the ability to run commands as other user
#

# Add user and group if not already exists.
getent group "$FLUX_GROUP" 2>&1 > /dev/null || groupadd -r $FLUX_GROUP --gid=$FLUX_USER_GID
getent passwd "$FLUX_USER" 2>&1 > /dev/null || useradd -r -g $FLUX_GROUP -G www-data --uid=$FLUX_USER_ID --home-dir=/var/www --shell=/bin/bash $FLUX_USER

if [ "$1" = 'php' ] || [ "$1" = 'composer' ]; then
    echo "Running as user \"$FLUX_USER\"..." # avoid time debugging
	exec gosu $FLUX_USER "$@"
	exit 0
fi

# Fallback to image default entry point
. docker-php-entrypoint
